import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"] ,
weight: ['400','600','700','500'],
variable: '--font-poppins',});

export const metadata: Metadata = {
  title: 'Event Organizer App',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/images/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>{children}</body>
    </html>
  </ClerkProvider>
   
  );
}
